services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - caddy_network
    container_name: app_client_server

  caddy:
    build:
      context: ./Caddy
    container_name: caddy_server
    ports:
      - "5000:5000"
    networks:
      - caddy_network
    restart: unless-stopped

networks:
  caddy_network:
    driver: bridge
