services:
  # server:
  #   build: ./server
  #   ports:
  #     - "8000:8000"
  client:
    build: ./client
    ports:
      - "3000:3000"
  # caddy:
  #   build: ./caddy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./caddy/Caddyfile:/etc/caddy/Caddyfile
  #   depends_on:
  #     - client
  #   restart: unless-stopped
  # database:
  #   image: "mysql"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #   volumes:
  #     - ./database:/var/lib/mysql

# volumes:
#   database_volume:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /database
