package models

import "time"

// ChallengeResponse contains the challenge and the signed response
type ChallengeResponse struct {
	ID        string `json:"user_id"`    // Public key or its ID
	PublicKey string `json:"public_key"` // Client's public key
	Signature string `json:"signature"`  // Signature generated by the client
	CreatedAt time.Time
	ExpiresAt time.Time
}

// ChallengeRequest contains the challenge request by the user
type ChallengeRequest struct {
	PublicKey string `json:"public_key"`
}

type ChallengeData struct {
	Challenge string
	CreatedAt time.Time
}
